version: '3.8'

services:

  users_service:
    image: node:18
    container_name: project-one-users-service
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5001:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:6.0
    container_name: project-one-users-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
